name: Steam Promo Checker

on:
  schedule:
    - cron: '0 11,23 * * *'
  
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.14' 
          enable-cache: true 
      
      - name: Sync dependencies
        run: uv sync --frozen
      
      - name: Database connection
        env:
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          DATABASE: ${{ secrets.DATABASE }}

      - name: Run pipeline
        run: uv run python main.py